import Head from 'next/head';
import ListProducts from '../components/Products/ListProducts';
import { getProducts } from '../utils/products.js';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ListProducts data={data} />;
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const { data } = await getProducts();

  // Pass data to the page via props
  return { props: { data } };
}
